# Generated by Django 6.0.3 on 2026-04-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_image', models.ImageField(upload_to='book/')),
                ('book_title', models.CharField(max_length=50)),
                ('book_des', models.TextField()),
            ],
        ),
    ]
