# Generated by Django 6.0.3 on 2026-04-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Addbooks', '0002_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
