# Generated by Django 6.0.3 on 2026-04-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addbooks', '0002_alter_book_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(upload_to='book/'),
        ),
    ]
