# Generated by Django 6.0.3 on 2026-04-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addbooks', '0003_remove_book_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mystery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_image', models.ImageField(upload_to='Mystery/')),
                ('book_title', models.CharField(max_length=50)),
                ('book_des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Programming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_image', models.ImageField(upload_to='Programming/')),
                ('book_title', models.CharField(max_length=50)),
                ('book_des', models.TextField()),
            ],
        ),
    ]
