# Generated by Django 6.0.3 on 2026-04-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addbooks', '0004_mystery_programming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_image', models.ImageField(upload_to='Business/')),
                ('book_title', models.CharField(max_length=50)),
                ('book_des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_image', models.ImageField(upload_to='history/')),
                ('book_title', models.CharField(max_length=50)),
                ('book_des', models.TextField()),
            ],
        ),
    ]
