# Generated by Django 6.0.3 on 2026-04-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addbooks', '0005_business_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_image', models.ImageField(upload_to='Electronics/')),
                ('book_title', models.CharField(max_length=50)),
                ('book_des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_image', models.ImageField(upload_to='Science/')),
                ('book_title', models.CharField(max_length=50)),
                ('book_des', models.TextField()),
            ],
        ),
    ]
