# Generated by Django 6.0.3 on 2026-04-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addbooks', '0006_electronics_science'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_image', models.ImageField(upload_to='Story/')),
                ('book_title', models.CharField(max_length=50)),
                ('book_author', models.CharField(default='Unknown', max_length=50)),
                ('book_des', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='book_author',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='electronics',
            name='book_author',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='history',
            name='book_author',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='mystery',
            name='book_author',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='programming',
            name='book_author',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='science',
            name='book_author',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
