# Generated by Django 6.0.3 on 2026-05-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addbooks', '0009_issuedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.AddField(
            model_name='business',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.AddField(
            model_name='electronics',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.AddField(
            model_name='history',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.AddField(
            model_name='mystery',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.AddField(
            model_name='programming',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.AddField(
            model_name='science',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.AddField(
            model_name='story',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.DeleteModel(
            name='IssuedBook',
        ),
    ]
