# Generated by Django 6.0.3 on 2026-05-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Addbooks', '0003_alter_book_book_image'),
        ('Addbooks', '0010_book_book_pdf_business_book_pdf_electronics_book_pdf_and_more'),
    ]

    operations = [
    ]
