# Generated by Django 6.0.3 on 2026-05-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addbooks', '0012_book_expiry_date_book_is_rented_book_renter_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electronics',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='history',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mystery',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programming',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='science',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
