# Generated by Django 6.0.3 on 2026-05-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addbooks', '0013_book_is_verified_business_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rented_books',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='total_books',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='business',
            name='rented_books',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='total_books',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='electronics',
            name='rented_books',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electronics',
            name='total_books',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='history',
            name='rented_books',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='total_books',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mystery',
            name='rented_books',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mystery',
            name='total_books',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='programming',
            name='rented_books',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='programming',
            name='total_books',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='science',
            name='rented_books',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='science',
            name='total_books',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='story',
            name='rented_books',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='total_books',
            field=models.IntegerField(default=1),
        ),
    ]
